// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseEditor():Promise<string>;

export function ChooseFont():Promise<string>;

export function GetInitialFile():Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function LoadFile(arg1:string):Promise<main.LoadResult>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenInNewInstance(arg1:string):Promise<void>;

export function ParseMarkdownWithDiff(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectFile():Promise<string>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function WatchFile(arg1:string):Promise<void>;
