// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseEditor() {
  return window['go']['main']['App']['ChooseEditor']();
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenInNewInstance(arg1) {
  return window['go']['main']['App']['OpenInNewInstance'](arg1);
}

export function ParseMarkdownWithDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['ParseMarkdownWithDiff'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function UnwatchFile(arg1) {
  return window['go']['main']['App']['UnwatchFile'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}
